\connect dacodes_db

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Courses" (
    "Id" uuid NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Code" text NULL,
    "Mandatory_courses" uuid[] NULL,
    "Mandatory_courses_code" text[] NULL,
    "Credits" integer NOT NULL,
    "Created_by" uuid NOT NULL,
    "Updated_by" uuid NOT NULL,
    "Approval_score" real NOT NULL,
    "Active" boolean NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Active" boolean NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Lessons" (
    "Id" uuid NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Question_details" text NULL,
    "Code" text NULL,
    "Order" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Hours" integer NOT NULL,
    "Score" integer NOT NULL,
    "CourseFK" uuid NOT NULL,
    "Created_by" uuid NOT NULL,
    "Updated_by" uuid NOT NULL,
    "Active" boolean NOT NULL,
    "Aproval_score" integer NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lessons_Courses_CourseFK" FOREIGN KEY ("CourseFK") REFERENCES "Courses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Lastname" text NULL,
    "Password" text NOT NULL,
    "Cellphone" text NULL,
    "Email" text NOT NULL,
    "Status" text NULL,
    "Active" boolean NOT NULL,
    "RoleFK" uuid NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    "CourseId" uuid NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Users_Roles_RoleFK" FOREIGN KEY ("RoleFK") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Questions" (
    "Id" uuid NOT NULL,
    "Description" text NULL,
    "Code" text NULL,
    "Score" integer NOT NULL,
    "LessonFK" uuid NOT NULL,
    "Type_question" text NULL,
    "Created_by" uuid NOT NULL,
    "Active" boolean NOT NULL,
    "Answers" text[] NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Questions_Lessons_LessonFK" FOREIGN KEY ("LessonFK") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tokens" (
    "Id" uuid NOT NULL,
    "UserFK" uuid NOT NULL,
    "Access_token" text NULL,
    "Refresh_token" text NULL,
    "Access_token_expires_at" bigint NOT NULL,
    "Issued_at" bigint NOT NULL,
    "Refresh_token_expires_in" bigint NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Tokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tokens_Users_UserFK" FOREIGN KEY ("UserFK") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Choices" (
    "Id" uuid NOT NULL,
    "QuestionFK" uuid NOT NULL,
    "Is_correct" boolean NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    "QuestionId" uuid NULL,
    CONSTRAINT "PK_Choices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Choices_Lessons_QuestionFK" FOREIGN KEY ("QuestionFK") REFERENCES "Lessons" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Choices_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Enrollments" (
    "Id" uuid NOT NULL,
    "UserFK" uuid NOT NULL,
    "CourseFK" uuid NOT NULL,
    "Lesson_scoreFK" uuid NOT NULL,
    "Date_of_enrollment" timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "Date_of_completation" timestamp without time zone NOT NULL,
    "Total_score" real NOT NULL,
    "Status" text NULL,
    "Active" boolean NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Enrollments_Courses_CourseFK" FOREIGN KEY ("CourseFK") REFERENCES "Courses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Enrollments_Users_UserFK" FOREIGN KEY ("UserFK") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Lesson_scores" (
    "Id" uuid NOT NULL,
    "EnrollmentFK" uuid NOT NULL,
    "LessonFK" uuid NOT NULL,
    "Lesson_result" real NOT NULL,
    "Successful_answers" integer NOT NULL,
    "Unsuccessful_answers" integer NOT NULL,
    "Created_at" timestamp without time zone NOT NULL,
    "Updated_at" timestamp without time zone NULL,
    CONSTRAINT "PK_Lesson_scores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lesson_scores_Enrollments_EnrollmentFK" FOREIGN KEY ("EnrollmentFK") REFERENCES "Enrollments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Lesson_scores_Lessons_LessonFK" FOREIGN KEY ("LessonFK") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Choices_QuestionFK" ON "Choices" ("QuestionFK");

CREATE INDEX "IX_Choices_QuestionId" ON "Choices" ("QuestionId");

CREATE UNIQUE INDEX "IX_Courses_Code" ON "Courses" ("Code");

CREATE UNIQUE INDEX "IX_Courses_Name" ON "Courses" ("Name");

CREATE INDEX "IX_Enrollments_CourseFK" ON "Enrollments" ("CourseFK");

CREATE UNIQUE INDEX "IX_Enrollments_Lesson_scoreFK" ON "Enrollments" ("Lesson_scoreFK");

CREATE INDEX "IX_Enrollments_UserFK" ON "Enrollments" ("UserFK");

CREATE INDEX "IX_Lesson_scores_EnrollmentFK" ON "Lesson_scores" ("EnrollmentFK");

CREATE INDEX "IX_Lesson_scores_LessonFK" ON "Lesson_scores" ("LessonFK");

CREATE INDEX "IX_Lessons_CourseFK" ON "Lessons" ("CourseFK");

CREATE INDEX "IX_Questions_LessonFK" ON "Questions" ("LessonFK");

CREATE INDEX "IX_Tokens_UserFK" ON "Tokens" ("UserFK");

CREATE INDEX "IX_Users_CourseId" ON "Users" ("CourseId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE INDEX "IX_Users_RoleFK" ON "Users" ("RoleFK");

ALTER TABLE "Enrollments" ADD CONSTRAINT "FK_Enrollments_Lesson_scores_Lesson_scoreFK" FOREIGN KEY ("Lesson_scoreFK") REFERENCES "Lesson_scores" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20191030042110_initial_migration', '3.0.0');

